[package]
name = "pcb-rs"
version = "0.0.0"
edition = "2021"

[lib]
name = "pcb_rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcb-rs-macros = { path = "../pcb-rs-macros" }
pcb-rs-traits = { path = "../pcb-rs-traits" }