[package]
name = "pcb-rs-macros"
version = "0.0.0"
edition = "2021"

[lib]
name = "pcb_rs_macros"
proc-macro = true

[dependencies]
syn = {version = "1.0.82", features=["extra-traits"] }
quote = "1.0.10"
proc-macro2 = "1.0.33"
pcb-rs-traits = {path="../pcb-rs-traits"}