[package]
name = "pcb-rs-macros"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "pcb_rs_macros"
proc-macro = true

[dependencies]
