[package]
name = "pcb-rs-tests"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcb-rs = { path = "../pcb-rs" }