[package]
name = "pcb-rs-traits"
version = "0.0.0"
edition = "2021"

[lib]
name = "pcb_rs_traits"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
downcast-rs = "1.2.0"